### PR TITLE
Tamari gray/issue105

### LINKED ISSUE #105: Game Tile overflows on smaller screens + welcome screen
**Describe the bug**
Screen Shot 2020-09-05 at 7 01 09 pm

there is overflowing on welcome screen aswell

**To Reproduce**
Run on a small screen, eg. the screenshot is from an iPhone SE.

### PR DESCRIPTION
**Pull request by tamari-gray**
fixes #105

### CODE REVIEW

File: lib/screens/lobby/created_game_tile.dart [hunk 1]
```diff
@@ -49,14 +48,6 @@ class GameTile extends StatelessWidget {
                           ),
                         ),
                       ),
-                      Text(
```
Comment (tamari-gray) [inline lib/screens/lobby/created_game_tile.dart:52]: looks better without this, tiles were abit information heavy

File: lib/utilities/validators.dart [hunk 2]
```diff
@@ -1,3 +1,11 @@
-final oneToFifteenChars = (String value) => value.isEmpty
```
Comment (tamari-gray) [inline lib/utilities/validators.dart:1]: made title to be 8 characters to fit inside game tile and prevent overflowing

**Review by tamari-gray — COMMENTED** [review]
noice

**Comment by tamari-gray** [comment]
gtg!

**Comment by tamari-gray** [comment]
u da man
