### PR TITLE
show text in loading indicator to give user more information

### LINKED ISSUE #131: show text in loading indicator to give user more information
### problem
currently the loading indicator only shows an icon animation.
This can give a user the wrong idea (especially in lobby screen)

### solution
add text to loading indicator widget to give user more information e.g "finding games to play" for lobby screen

### referenced bug find
Another quick note: The animation that was used after signing in, that I took to be the waiting indicator type animation, tricked me into thinking I needed to wait when I got to the Lobby: 

Screen Shot 2020-10-06 at 12 25 33 am

_Originally posted by @nickmeinhold in https://github.com/tamari-gray/niira/pull/129#issuecomment-703633342_

### PR DESCRIPTION
**Pull request by tamari-gray**
Fixes #131

### CODE REVIEW

File: lib/loading.dart [hunk 1]
```diff
@@ -2,18 +2,36 @@ import 'package:flutter/material.dart';
...
+        mainAxisAlignment: MainAxisAlignment.center,
+        children: <Widget>[
+          SpinKitPulse(
+            key: Key('loading_indicator'),
+            color: Theme.of(context).primaryColor,
+            size: 100.0,
+          ),
+          Padding(
+            padding: EdgeInsets.fromLTRB(25, 50, 25, 0),
+            child: Directionality(
```
Comment (tamari-gray) [inline lib/loading.dart:23]: was throwing error if i didnt wrap text in a directionality widget

File: lib/screens/lobby/lobby.dart [hunk 2]
```diff
@@ -40,11 +40,11 @@ class LobbyScreen extends StatelessWidget {
       body: FutureBuilder<Location>(
           future: context.watch<LocationService>().getUsersCurrentLocation(),
           builder: (context, snapshot) {
-            if (snapshot.hasData == false) {
-              return Loading();
-            } else {
-              return ListOfCreatedGames(snapshot.data);
-            }
+            return snapshot.hasData
```
Comment (tamari-gray) [inline lib/screens/lobby/lobby.dart:43]: little refactor, couldnt help myself
